// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT-PXPSKmHtpl2BdTeUgubv-z6i3K6sd4',
    appId: '1:733786203860:web:21dc1ee638b8db712ffd41',
    messagingSenderId: '733786203860',
    projectId: 'flutter-app-schedule-learning',
    authDomain: 'flutter-app-schedule-learning.firebaseapp.com',
    databaseURL: 'https://flutter-app-schedule-learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-schedule-learning.appspot.com',
    measurementId: 'G-S0LX96E8FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhYTkP-BJ475BuQ_No_Qu-0OlUcC-rM2Y',
    appId: '1:733786203860:android:ec2d853b89bd1c3c2ffd41',
    messagingSenderId: '733786203860',
    projectId: 'flutter-app-schedule-learning',
    databaseURL: 'https://flutter-app-schedule-learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-schedule-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTCyN7my2l-L1tqGq3LZBWj7g_2ZXxI8E',
    appId: '1:733786203860:ios:49fbf6e35e7397e82ffd41',
    messagingSenderId: '733786203860',
    projectId: 'flutter-app-schedule-learning',
    databaseURL: 'https://flutter-app-schedule-learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-schedule-learning.appspot.com',
    iosBundleId: 'com.example.appScheduleFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTCyN7my2l-L1tqGq3LZBWj7g_2ZXxI8E',
    appId: '1:733786203860:ios:49fbf6e35e7397e82ffd41',
    messagingSenderId: '733786203860',
    projectId: 'flutter-app-schedule-learning',
    databaseURL: 'https://flutter-app-schedule-learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-schedule-learning.appspot.com',
    iosBundleId: 'com.example.appScheduleFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT-PXPSKmHtpl2BdTeUgubv-z6i3K6sd4',
    appId: '1:733786203860:web:da1f392f07ca23b92ffd41',
    messagingSenderId: '733786203860',
    projectId: 'flutter-app-schedule-learning',
    authDomain: 'flutter-app-schedule-learning.firebaseapp.com',
    databaseURL: 'https://flutter-app-schedule-learning-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-app-schedule-learning.appspot.com',
    measurementId: 'G-4QVW6CH99N',
  );
}
